### ISSUE TITLE
Firefox-cn每次更新, 配置文件都重置了哎, 安装都插件扩展都没用了, 需要重新安装

### ISSUE THREAD

**Issue by zhoujin7** [chawyehsu/dorado#107]
Firefox-cn每次更新, 配置文件都重置了哎, 安装都插件扩展都没用了, 需要重新安装

**Comment by Ni1fheim** [comment]
地址栏输入 `about:profiles` ，每一份配置文件应该都在，选择常用的那份为默认，重启浏览器。

**Comment by kidonng** [comment]
lukesampson/scoop-extras#4377

**Comment by hhaoao** [comment]
我写了个只下载,不安装小工具.用pyintaller 打包起来了.希望帮助有需要的人. https://github.com/hhaoao/rein
