### ISSUE TITLE
QQ安装完成后，打开提示QQ安全组件异常

### ISSUE THREAD

**Issue by 345000346** [chawyehsu/dorado#11]
RT

**Comment by h404bi** [comment]
Q盾的问题，这个暂时无解，只能先用原始安装包安装一遍，生成 QQProtect 等文件，再卸载重新安装 Scoop 的版本。见：https://www.twblogs.net/a/5b7e0c622b7177683854fcc3/zh-cn

也许我应该把 tim 和 qq 移回 experiment

**Comment by yh-cs** [comment]
tim也有同样的问题

**Comment by dodorz** [comment]
TIM有类似问题，且重装原始安装包再卸载也不奏效。
![image](https://user-images.githubusercontent.com/1287424/63660517-5c381f00-c7e9-11e9-8caa-5d3d85e9df24.png)

**Comment by chawyehsu** [comment]
Fixed by https://github.com/chawyehsu/dorado/commit/36e3ff0b3f7ab40eb0e329cb799b0c06cd9a964e
