### ISSUE TITLE
[Request]请求添加Quicker

### ISSUE THREAD

**Issue by nanbowaner** [chawyehsu/dorado#125]
##App name
Quicker
##description
为常用操作建立捷径，让效率触手可及!
##website
https://getquicker.net
##where to download
https://getquicker.net/Download

**Comment by zhoujin7** [comment]
我的仓库已经添加了quicker
https://github.com/zhoujin7/tomato
@nanbowaner

**Comment by whitewatercn** [comment]
赞，感谢大佬，已经用上quicker了

> 我的仓库已经添加了quicker https://github.com/zhoujin7/tomato @nanbowaner
