### ISSUE TITLE
[Request] 可以将下面这四个应用程序添加到你的bucket里面吗?

### ISSUE THREAD

**Issue by SylleoYr** [chawyehsu/dorado#130]
我对照官方 wiki 编写了下面这四个 manifests，并且在我的机器上测试通过，想提交到你的仓库中，但是担心突然的 PR 带来的不礼貌，以及避免引起未知的冲突和不必要的麻烦（我没有测试过 Excavator），所以开启了这个 issue。

### Bandizip 6

extras 里面的是最新 7.x 版本的，7.x 版本开始收费并且包含广告（无恶意），所以我根据 7.x 的 manifest 为 6.27 版本的 Bandizip 编写了 manifest：

```json
{
    "version": "6.27",
    "description": "The old version 6.x of Bandizip",
    "homepage": "http://www.bandisoft.com/bandizip/",
    "license": {
        "identifier": "Freeware",
        "url": "https://en.bandisoft.com/bandizip/eula/"
    },
    "url": "https://ca-dl.bandisoft.com/bandizip.old/BANDIZIP6-PORTABLE.ZIP",
    "hash": "4D871837DCDA579B6F8807783438C4EC0244EF0A6A37A45CF6C02CB2E17CF24B",
    "architecture": {
        "64bit": {
            "pre_install": "Rename-Item \"$dir\\Bandizip64.exe\" 'Bandizip.exe'"
        },
        "32bit": {
            "pre_install": "Rename-Item \"$dir\\Bandizip32.exe\" 'Bandizip.exe'"
        }
    },
    "installer": {
        "script": [
            "if (!(Test-Path \"$persist_dir\\Bandizip.ini\")) { New-Item \"$dir\\Bandizip.ini\" | Out-Null }"
        ]
    },
    "bin": "Bandizip.exe",
    "shortcuts": [
        [
            "Bandizip.exe",
            "Bandizip 6"
        ]
    ],
    "persist": "Bandizip.ini",
    "notes": [
        "This is a old version 6.x of Bandizip, if you want the latest version, use the extras bucket or go to its homepage."
    ]
}
```

### Capslock+

一个用 AHK 编写的 Capslock 键增强软件

```json
{
    "homepage": "https://capslox.com/capslock-plus/",
    "description": "A productivity tool that provides various functions by enhancing the Caps Lock key into a modifier key.",
    "version": "3.1.0",
    "license": "Unknown",
    "url": "https://dl.capslox.com/app/Capslock%2B_v3.1.0.exe",
    "hash": "e2283e6045ae0f78f116a9210b18542557e819f27d59f07ef73f9861b9ee13c6",
    "shortcuts": [
        [
            "Capslockplus.exe",
            "CapsLock+"
        ]
    ],
    "pre_install": [
        "if (-not (Test-Path \"$persist_dir\\CapsLock+settings.ini\")) {",
        "    \";------------ Encoding: UTF-16 ------------\" | Out-File \"$persist_dir\\CapsLock+settings.ini\"",
        "}",
        "if (-not (Test-Path \"$persist_dir\\CapsLock+winsInfosRecorder.ini\")) {",
        "    \";------------ Encoding: UTF-16 ------------\" | Out-File \"$persist_dir\\CapsLock+winsInfosRecorder.ini\"",
        "}",
        "Rename-Item -Path \"$dir\\Capslock%2B_v$version.exe\" -NewName \"Capslockplus.exe\""
    ],
    "persisit": [
        "CapsLock+settings.ini",
        "CapsLock+winsInfosRecorder.ini",
        "loadScript"
    ],
    "checkver": {
        "url": "https://capslox.com/capslock-plus/#%E7%89%88%E6%9C%AC%E5%8E%86%E5%8F%B2",
        "regex": "<strong>v([\\d.]+)\\s\\|"
    },
    "autoupdate": {
        "url": "https://dl.capslox.com/app/Capslock%2B_v$version.exe"
    },
    "notes": [
        "Disclaimer: Capslock+ is a paid software, though it's not compulsory. Feel free to make a pledge based on your using time and frequency.",
        "Payment page: http://cjkis.me/payment/"
    ]
}
```

### Electerm

开源的 SSH client

```json
{
    "version": "1.3.31",
    "description": "Terminal/ssh/serial port/sftp client(linux, mac, win)",
    "homepage": "https://electerm.github.io/electerm",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/electerm/electerm/releases/download/v1.3.31/electerm-1.3.31-win-x64.tar.gz",
            "hash": "af74c2d33f656098dbc50a8292eb9195633cb25c97092f8d1c89a7c7613f8a71"
        }
    },
    "extract_dir": "electerm-1.3.31-win-x64",
    "bin": "electerm.exe",
    "shortcuts": [
        [
            "electerm.exe",
            "Electerm"
        ]
    ],
    "checkver": {
        "github": "https://github.com/electerm/electerm"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/electerm/electerm/releases/download/v$version/electerm-$version-win-x64.tar.gz",
                "extract_dir": "electerm-$version-win-x64"
            }
        }
    },
    "notes": "We do not persist your data."
}
```

### pyenv-win

Windows 平台上的pyenv，一个 Python 的版本管理工具，参照 psutils 的 manifest 编写的

```json
{
    "homepage": "https://github.com/pyenv-win/pyenv-win",
    "description": "A simple python version management tool for Windows",
    "version": "0.2020.05.21",
    "license": "MIT",
    "url": "https://github.com/pyenv-win/pyenv-win/archive/f0f503cd15262b8863e00836605d538ca9f9c0e1.zip",
    "extract_dir": "pyenv-win-f0f503cd15262b8863e00836605d538ca9f9c0e1",
    "hash": "af2db0702cad8b78aab1dbc23b578dc6111ffa6c5eef22e02301c1642d6a46b1",
    "env_set": {
        "PYENV": "$dir\\pyenv-win"
    },
    "env_add_path": [
        "pyenv-win\\bin",
        "pyenv-win\\shims"
    ],
    "pre_install": [
        "if (-not (Test-Path \"$persist_dir\\pyenv-win\\install_cache\")) {",
        "    New-Item -ItemType Directory -Path \"$persist_dir\\pyenv-win\\install_cache\" -Force",
        "}",
        "if (-not (Test-Path \"$persist_dir\\pyenv-win\\shims\")) {",
        "    New-Item -ItemType Directory -Path \"$persist_dir\\pyenv-win\\shims\" -Force",
        "}",
        "if (-not (Test-Path \"$persist_dir\\pyenv-win\\versions\")) {",
        "    New-Item -ItemType Directory -Path \"$persist_dir\\pyenv-win\\versions\" -Force",
        "}",
        "if (-not (Test-Path \"$persist_dir\\pyenv-win\\version\")) {",
        "    New-Item -ItemType File -Path \"$persist_dir\\pyenv-win\\version\" -Force",
        "}",
        "if (-not (Test-Path \"$persist_dir\\pyenv-win\\exec.bat\")) {",
        "    New-Item -ItemType File -Path \"$persist_dir\\pyenv-win\\exec.bat\" -Force",
        "}"
    ],
    "persist": [
        "pyenv-win\\install_cache",
        "pyenv-win\\shims",
        "pyenv-win\\versions",
        "pyenv-win\\version",
        "pyenv-win\\exec.bat"
    ],
    "notes": [
        "The environment variable 'PYENV' has been added to your environment.",
        "\"$dir\\pyenv-win\\bin\" and \"$persist_dir\\pyenv-win\\shims\" have been added to your path.",
        "Run 'pyenv' to see list of commands pyenv supports.",
        "If you want to install from a mirror, set the environment variables 'PYTHON_BUILD_MIRROR_URL' to the mirror link",
        "**WARNING:**",
        "After (un)installing or switching any python version, you must run 'pyenv rehash' to update pyenv with the new python version.",
        "    Note: This command must be run outside of the pyenv folder.",
        "For more questions, see https://github.com/pyenv-win/pyenv-win#faq"
    ],
    "checkver": {
        "url": "https://github.com/pyenv-win/pyenv-win/commits/master.atom",
        "regex": "(?s)>(\\d+)-(\\d+)-(\\d+)T.*?/(?<sha>[0-9a-f]{40})",
        "replace": "0.${1}.${2}.${3}"
    },
    "autoupdate": {
        "url": "https://github.com/pyenv-win/pyenv-win/archive/$matchSha.zip",
        "extract_dir": "pyenv-win-$matchSha"
    }
}
```
Thanks :D

**Comment by AkariiinMKII** [comment]
旧版本的bandizip推荐提交到[versions](https://github.com/scoopinstaller/versions)这个bucket

**Comment by SylleoYr** [comment]
> 
> 
> 旧版本的bandizip推荐提交到[versions](https://github.com/scoopinstaller/versions)这个bucket

ok, I'll do that.

**Comment by DestinyHunter** [comment]
既然 pyenv  要加入,  那么 go, done, 的 多版本管理工具也加入吧, mvm 已经有了
go: [https://github.com/voidint/g](url)
dvm: [https://github.com/justjavac/dvm](url)

**Comment by xiaomao111** [comment]
> 我对照官方 wiki 编写了下面这四个 manifests，并且在我的机器上测试通过，想提交到你的仓库中，但是担心突然的 PR 带来的不礼貌，以及避免引起未知的冲突和不必要的麻烦（我没有测试过 Excavator），所以开启了这个 issue。
> 
> ### Bandizip 6
> extras 里面的是最新 7.x 版本的，7.x 版本开始收费并且包含广告（无恶意），所以我根据 7.x 的 manifest 为 6.27 版本的 Bandizip 编写了 manifest：
> 
> ```json
> {
>     "version": "6.27",
>     "description": "The old version 6.x of Bandizip",
>     "homepage": "http://www.bandisoft.com/bandizip/",
>     "license": {
>         "identifier": "Freeware",
>         "url": "https://en.bandisoft.com/bandizip/eula/"
>     },
>     "url": "https://ca-dl.bandisoft.com/bandizip.old/BANDIZIP6-PORTABLE.ZIP",
>     "hash": "4D871837DCDA579B6F8807783438C4EC0244EF0A6A37A45CF6C02CB2E17CF24B",
>     "architecture": {
>         "64bit": {
>             "pre_install": "Rename-Item \"$dir\\Bandizip64.exe\" 'Bandizip.exe'"
>         },
>         "32bit": {
>             "pre_install": "Rename-Item \"$dir\\Bandizip32.exe\" 'Bandizip.exe'"
>         }
>     },
>     "installer": {
>         "script": [
>             "if (!(Test-Path \"$persist_dir\\Bandizip.ini\")) { New-Item \"$dir\\Bandizip.ini\" | Out-Null }"
>         ]
>     },
>     "bin": "Bandizip.exe",
>     "shortcuts": [
>         [
>             "Bandizip.exe",
>             "Bandizip 6"
>         ]
>     ],
>     "persist": "Bandizip.ini",
>     "notes": [
>         "This is a old version 6.x of Bandizip, if you want the latest version, use the extras bucket or go to its homepage."
>     ]
> }
> ```
> 
> ### Capslock+
> 一个用 AHK 编写的 Capslock 键增强软件
> 
> ```json
> {
>     "homepage": "https://capslox.com/capslock-plus/",
>     "description": "A productivity tool that provides various functions by enhancing the Caps Lock key into a modifier key.",
>     "version": "3.1.0",
>     "license": "Unknown",
>     "url": "https://dl.capslox.com/app/Capslock%2B_v3.1.0.exe",
>     "hash": "e2283e6045ae0f78f116a9210b18542557e819f27d59f07ef73f9861b9ee13c6",
>     "shortcuts": [
>         [
>             "Capslockplus.exe",
>             "CapsLock+"
>         ]
>     ],
>     "pre_install": [
>         "if (-not (Test-Path \"$persist_dir\\CapsLock+settings.ini\")) {",
>         "    \";------------ Encoding: UTF-16 ------------\" | Out-File \"$persist_dir\\CapsLock+settings.ini\"",
>         "}",
>         "if (-not (Test-Path \"$persist_dir\\CapsLock+winsInfosRecorder.ini\")) {",
>         "    \";------------ Encoding: UTF-16 ------------\" | Out-File \"$persist_dir\\CapsLock+winsInfosRecorder.ini\"",
>         "}",
>         "Rename-Item -Path \"$dir\\Capslock%2B_v$version.exe\" -NewName \"Capslockplus.exe\""
>     ],
>     "persisit": [
>         "CapsLock+settings.ini",
>         "CapsLock+winsInfosRecorder.ini",
>         "loadScript"
>     ],
>     "checkver": {
>         "url": "https://capslox.com/capslock-plus/#%E7%89%88%E6%9C%AC%E5%8E%86%E5%8F%B2",
>         "regex": "<strong>v([\\d.]+)\\s\\|"
>     },
>     "autoupdate": {
>         "url": "https://dl.capslox.com/app/Capslock%2B_v$version.exe"
>     },
>     "notes": [
>         "Disclaimer: Capslock+ is a paid software, though it's not compulsory. Feel free to make a pledge based on your using time and frequency.",
>         "Payment page: http://cjkis.me/payment/"
>     ]
> }
> ```
> 
> ### Electerm
> 开源的 SSH client
> 
> ```json
> {
>     "version": "1.3.31",
>     "description": "Terminal/ssh/serial port/sftp client(linux, mac, win)",
>     "homepage": "https://electerm.github.io/electerm",
>     "license": "MIT",
>     "architecture": {
>         "64bit": {
>             "url": "https://github.com/electerm/electerm/releases/download/v1.3.31/electerm-1.3.31-win-x64.tar.gz",
>             "hash": "af74c2d33f656098dbc50a8292eb9195633cb25c97092f8d1c89a7c7613f8a71"
>         }
>     },
>     "extract_dir": "electerm-1.3.31-win-x64",
>     "bin": "electerm.exe",
>     "shortcuts": [
>         [
>             "electerm.exe",
>             "Electerm"
>         ]
>     ],
>     "checkver": {
>         "github": "https://github.com/electerm/electerm"
>     },
>     "autoupdate": {
>         "architecture": {
>             "64bit": {
>                 "url": "https://github.com/electerm/electerm/releases/download/v$version/electerm-$version-win-x64.tar.gz",
>                 "extract_dir": "electerm-$version-win-x64"
>             }
>         }
>     },
>     "notes": "We do not persist your data."
> }
> ```
> 
> ### pyenv-win
> Windows 平台上的pyenv，一个 Python 的版本管理工具，参照 psutils 的 manifest 编写的
> 
> ```json
> {
>     "homepage": "https://github.com/pyenv-win/pyenv-win",
>     "description": "A simple python version management tool for Windows",
>     "version": "0.2020.05.21",
>     "license": "MIT",
>     "url": "https://github.com/pyenv-win/pyenv-win/archive/f0f503cd15262b8863e00836605d538ca9f9c0e1.zip",
>     "extract_dir": "pyenv-win-f0f503cd15262b8863e00836605d538ca9f9c0e1",
>     "hash": "af2db0702cad8b78aab1dbc23b578dc6111ffa6c5eef22e02301c1642d6a46b1",
>     "env_set": {
>         "PYENV": "$dir\\pyenv-win"
>     },
>     "env_add_path": [
>         "pyenv-win\\bin",
>         "pyenv-win\\shims"
>     ],
>     "pre_install": [
>         "if (-not (Test-Path \"$persist_dir\\pyenv-win\\install_cache\")) {",
>         "    New-Item -ItemType Directory -Path \"$persist_dir\\pyenv-win\\install_cache\" -Force",
>         "}",
>         "if (-not (Test-Path \"$persist_dir\\pyenv-win\\shims\")) {",
>         "    New-Item -ItemType Directory -Path \"$persist_dir\\pyenv-win\\shims\" -Force",
>         "}",
>         "if (-not (Test-Path \"$persist_dir\\pyenv-win\\versions\")) {",
>         "    New-Item -ItemType Directory -Path \"$persist_dir\\pyenv-win\\versions\" -Force",
>         "}",
>         "if (-not (Test-Path \"$persist_dir\\pyenv-win\\version\")) {",
>         "    New-Item -ItemType File -Path \"$persist_dir\\pyenv-win\\version\" -Force",
>         "}",
>         "if (-not (Test-Path \"$persist_dir\\pyenv-win\\exec.bat\")) {",
>         "    New-Item -ItemType File -Path \"$persist_dir\\pyenv-win\\exec.bat\" -Force",
>         "}"
>     ],
>     "persist": [
>         "pyenv-win\\install_cache",
>         "pyenv-win\\shims",
>         "pyenv-win\\versions",
>         "pyenv-win\\version",
>         "pyenv-win\\exec.bat"
>     ],
>     "notes": [
>         "The environment variable 'PYENV' has been added to your environment.",
>         "\"$dir\\pyenv-win\\bin\" and \"$persist_dir\\pyenv-win\\shims\" have been added to your path.",
>         "Run 'pyenv' to see list of commands pyenv supports.",
>         "If you want to install from a mirror, set the environment variables 'PYTHON_BUILD_MIRROR_URL' to the mirror link",
>         "**WARNING:**",
>         "After (un)installing or switching any python version, you must run 'pyenv rehash' to update pyenv with the new python version.",
>         "    Note: This command must be run outside of the pyenv folder.",
>         "For more questions, see https://github.com/pyenv-win/pyenv-win#faq"
>     ],
>     "checkver": {
>         "url": "https://github.com/pyenv-win/pyenv-win/commits/master.atom",
>         "regex": "(?s)>(\\d+)-(\\d+)-(\\d+)T.*?/(?<sha>[0-9a-f]{40})",
>         "replace": "0.${1}.${2}.${3}"
>     },
>     "autoupdate": {
>         "url": "https://github.com/pyenv-win/pyenv-win/archive/$matchSha.zip",
>         "extract_dir": "pyenv-win-$matchSha"
>     }
> }
> ```
> 
> Thanks :D



> 我对照官方 wiki 编写了下面这四个 manifests，并且在我的机器上测试通过，想提交到你的仓库中，但是担心突然的 PR 带来的不礼貌，以及避免引起未知的冲突和不必要的麻烦（我没有测试过 Excavator），所以开启了这个 issue。
> 
> ### 班迪拉链 6
> extras 里面的是最新 7.x 版本的，7.x 版本开始收费并且包含广告（无恶意），所以我根据 7.x 的 manifest 为 6.27 版本的 Bandizip 编写了 manifest：
> 
> ```json
> {
>     "version": "6.27",
>     "description": "The old version 6.x of Bandizip",
>     "homepage": "http://www.bandisoft.com/bandizip/",
>     "license": {
>         "identifier": "Freeware",
>         "url": "https://en.bandisoft.com/bandizip/eula/"
>     },
>     "url": "https://ca-dl.bandisoft.com/bandizip.old/BANDIZIP6-PORTABLE.ZIP",
>     "hash": "4D871837DCDA579B6F8807783438C4EC0244EF0A6A37A45CF6C02CB2E17CF24B",
>     "architecture": {
>         "64bit": {
>             "pre_install": "Rename-Item \"$dir\\Bandizip64.exe\" 'Bandizip.exe'"
>         },
>         "32bit": {
>             "pre_install": "Rename-Item \"$dir\\Bandizip32.exe\" 'Bandizip.exe'"
>         }
>     },
>     "installer": {
>         "script": [
>             "if (!(Test-Path \"$persist_dir\\Bandizip.ini\")) { New-Item \"$dir\\Bandizip.ini\" | Out-Null }"
>         ]
>     },
>     "bin": "Bandizip.exe",
>     "shortcuts": [
>         [
>             "Bandizip.exe",
>             "Bandizip 6"
>         ]
>     ],
>     "persist": "Bandizip.ini",
>     "notes": [
>         "This is a old version 6.x of Bandizip, if you want the latest version, use the extras bucket or go to its homepage."
>     ]
> }
> ```
> 
> ### 卡普斯洛克+
> 一个用 AHK 编写的 Capslock 键增强软件
> 
> ```json
> {
>     "homepage": "https://capslox.com/capslock-plus/",
>     "description": "A productivity tool that provides various functions by enhancing the Caps Lock key into a modifier key.",
>     "version": "3.1.0",
>     "license": "Unknown",
>     "url": "https://dl.capslox.com/app/Capslock%2B_v3.1.0.exe",
>     "hash": "e2283e6045ae0f78f116a9210b18542557e819f27d59f07ef73f9861b9ee13c6",
>     "shortcuts": [
>         [
>             "Capslockplus.exe",
>             "CapsLock+"
>         ]
>     ],
>     "pre_install": [
>         "if (-not (Test-Path \"$persist_dir\\CapsLock+settings.ini\")) {",
>         "    \";------------ Encoding: UTF-16 ------------\" | Out-File \"$persist_dir\\CapsLock+settings.ini\"",
>         "}",
>         "if (-not (Test-Path \"$persist_dir\\CapsLock+winsInfosRecorder.ini\")) {",
>         "    \";------------ Encoding: UTF-16 ------------\" | Out-File \"$persist_dir\\CapsLock+winsInfosRecorder.ini\"",
>         "}",
>         "Rename-Item -Path \"$dir\\Capslock%2B_v$version.exe\" -NewName \"Capslockplus.exe\""
>     ],
>     "persisit": [
>         "CapsLock+settings.ini",
>         "CapsLock+winsInfosRecorder.ini",
>         "loadScript"
>     ],
>     "checkver": {
>         "url": "https://capslox.com/capslock-plus/#%E7%89%88%E6%9C%AC%E5%8E%86%E5%8F%B2",
>         "regex": "<strong>v([\\d.]+)\\s\\|"
>     },
>     "autoupdate": {
>         "url": "https://dl.capslox.com/app/Capslock%2B_v$version.exe"
>     },
>     "notes": [
>         "Disclaimer: Capslock+ is a paid software, though it's not compulsory. Feel free to make a pledge based on your using time and frequency.",
>         "Payment page: http://cjkis.me/payment/"
>     ]
> }
> ```
> 
> ### 电子
> 开源的 SSH 客户端
> 
> ```json
> {
>     "version": "1.3.31",
>     "description": "Terminal/ssh/serial port/sftp client(linux, mac, win)",
>     "homepage": "https://electerm.github.io/electerm",
>     "license": "MIT",
>     "architecture": {
>         "64bit": {
>             "url": "https://github.com/electerm/electerm/releases/download/v1.3.31/electerm-1.3.31-win-x64.tar.gz",
>             "hash": "af74c2d33f656098dbc50a8292eb9195633cb25c97092f8d1c89a7c7613f8a71"
>         }
>     },
>     "extract_dir": "electerm-1.3.31-win-x64",
>     "bin": "electerm.exe",
>     "shortcuts": [
>         [
>             "electerm.exe",
>             "Electerm"
>         ]
>     ],
>     "checkver": {
>         "github": "https://github.com/electerm/electerm"
>     },
>     "autoupdate": {
>         "architecture": {
>             "64bit": {
>                 "url": "https://github.com/electerm/electerm/releases/download/v$version/electerm-$version-win-x64.tar.gz",
>                 "extract_dir": "electerm-$version-win-x64"
>             }
>         }
>     },
>     "notes": "We do not persist your data."
> }
> ```
> 
> ### Pyenv-win
> Windows 平台上的pyenv，一个 Python 的版本管理工具，参照 psutils 的 manifest 编写的
> 
> ```json
> {
>     "homepage": "https://github.com/pyenv-win/pyenv-win",
>     "description": "A simple python version management tool for Windows",
>     "version": "0.2020.05.21",
>     "license": "MIT",
>     "url": "https://github.com/pyenv-win/pyenv-win/archive/f0f503cd15262b8863e00836605d538ca9f9c0e1.zip",
>     "extract_dir": "pyenv-win-f0f503cd15262b8863e00836605d538ca9f9c0e1",
>     "hash": "af2db0702cad8b78aab1dbc23b578dc6111ffa6c5eef22e02301c1642d6a46b1",
>     "env_set": {
>         "PYENV": "$dir\\pyenv-win"
>     },
>     "env_add_path": [
>         "pyenv-win\\bin",
>         "pyenv-win\\shims"
>     ],
>     "pre_install": [
>         "if (-not (Test-Path \"$persist_dir\\pyenv-win\\install_cache\")) {",
>         "    New-Item -ItemType Directory -Path \"$persist_dir\\pyenv-win\\install_cache\" -Force",
>         "}",
>         "if (-not (Test-Path \"$persist_dir\\pyenv-win\\shims\")) {",
>         "    New-Item -ItemType Directory -Path \"$persist_dir\\pyenv-win\\shims\" -Force",
>         "}",
>         "if (-not (Test-Path \"$persist_dir\\pyenv-win\\versions\")) {",
>         "    New-Item -ItemType Directory -Path \"$persist_dir\\pyenv-win\\versions\" -Force",
>         "}",
>         "if (-not (Test-Path \"$persist_dir\\pyenv-win\\version\")) {",
>         "    New-Item -ItemType File -Path \"$persist_dir\\pyenv-win\\version\" -Force",
>         "}",
>         "if (-not (Test-Path \"$persist_dir\\pyenv-win\\exec.bat\")) {",
>         "    New-Item -ItemType File -Path \"$persist_dir\\pyenv-win\\exec.bat\" -Force",
>         "}"
>     ],
>     "persist": [
>         "pyenv-win\\install_cache",
>         "pyenv-win\\shims",
>         "pyenv-win\\versions",
>         "pyenv-win\\version",
>         "pyenv-win\\exec.bat"
>     ],
>     "notes": [
>         "The environment variable 'PYENV' has been added to your environment.",
>         "\"$dir\\pyenv-win\\bin\" and \"$persist_dir\\pyenv-win\\shims\" have been added to your path.",
>         "Run 'pyenv' to see list of commands pyenv supports.",
>         "If you want to install from a mirror, set the environment variables 'PYTHON_BUILD_MIRROR_URL' to the mirror link",
>         "**WARNING:**",
>         "After (un)installing or switching any python version, you must run 'pyenv rehash' to update pyenv with the new python version.",
>         "    Note: This command must be run outside of the pyenv folder.",
>         "For more questions, see https://github.com/pyenv-win/pyenv-win#faq"
>     ],
>     "checkver": {
>         "url": "https://github.com/pyenv-win/pyenv-win/commits/master.atom",
>         "regex": "(?s)>(\\d+)-(\\d+)-(\\d+)T.*?/(?<sha>[0-9a-f]{40})",
>         "replace": "0.${1}.${2}.${3}"
>     },
>     "autoupdate": {
>         "url": "https://github.com/pyenv-win/pyenv-win/archive/$matchSha.zip",
>         "extract_dir": "pyenv-win-$matchSha"
>     }
> }
> ```
> 
> 谢谢:D

我可以放进自己的仓库并分享吗
