### ISSUE TITLE
【scoop的manifest问题】发现一个关于scoop的manifest文件的问题, architecture只有32位, 那么64位的系统不能安装上

### ISSUE THREAD

**Issue by zhoujin7** [chawyehsu/dorado#150]
【scoop的manifest问题】发现一个关于scoop的manifest文件的问题, architecture只有32位, 那么64位的系统不能安装上.
```json
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "32bit": {
                "url": "https://github.com/PyQt5/QtDesigner/releases/download/$version/QtDesigner_Windows_x86.7z"
            }
        }
    }
```
像上面这个, 因为它只有32位版本, 所以我只写了32位架构的文件下载路径, 如果是64位系统,不能安装上.
我刚刚试了, `'QtDesigner' doesn't support 64bit architecture!`

理论上所有32位的可执行文件, 都能在64位系统上运行, 所以scoop这个地方可不可以聪明一点呢? 目前我还是自己把architecture的32/64复制一遍吧.

**Comment by zhoujin7** [comment]
我发现自己走了弯路

**Comment by chawyehsu** [comment]
只有32位就直接用url，加architecture多此一举啊

**Comment by zhoujin7** [comment]
嗯咯 发现自己走了弯路 好久没写manifest了
