### ISSUE TITLE
clashweb@1.6.5: hash check failed

### ISSUE THREAD

**Issue by fomooerking** [chawyehsu/dorado#162]
安装clashweb版本失败如下
Download: Status Legend:
Download: (OK):download completed.
Checking hash of ClashWebRelease1.6.5.7z ... ERROR Hash check failed!
App:         dorado/clashweb
URL:         https://github.com/lzdnico/ClashWeb/releases/download/ClashWeb1.6.5/ClashWebRelease1.6.5.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    e6c8b63670100dfe30e026cb399929e0d2f953394e96ad6bebc8d87919029820
Actual:      f8f2202665e4fe37b53c19ca0783ecdbdb8404440948417808ad8d50092e0d76

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/chawyehsu/dorado/issues/new?title=clashweb%401.6.5%3a+hash+check+failed

**Comment by fomooerking** [comment]
我问过作者了，应该是这个版本他近期重新提交过，所以导致哈希值不一样，校验失败，无法安装

**Comment by kidonng** [comment]
Fixed in https://github.com/chawyehsu/dorado/pull/160
