### ISSUE TITLE
[Request]请求收录 Sandboxie

### ISSUE THREAD

**Issue by Fffdmin** [chawyehsu/dorado#164]
*Snadboxie*

Sandboxie is sandbox-based isolation software for 32- and 64-bit Windows NT-based operating systems. It was developed by Sophos (which acquired it from Invincea, which acquired it earlier from the original author Ronen Tzur). It creates a sandbox-like isolated operating environment in which applications can be run or installed without permanently modifying the local or mapped drive. An isolated virtual environment allows controlled testing of untrusted programs and web surfing.

*Download*
https://github.com/sandboxie-plus/Sandboxie

官方已开源并且提供 Portable 版本，请及时收录

**Comment by kidonng** [comment]
https://github.com/kidonng/sushi/blob/master/bucket/sandboxie-plus.json

**Comment by chawyehsu** [comment]
tracking https://github.com/ScoopInstaller/Extras/issues/9787
