### ISSUE TITLE
[Request]请收录RaiDrive

### ISSUE THREAD

**Issue by yiwenleo** [chawyehsu/dorado#166]
RaiDrive is great software to manage remote files. 
RaiDrive是个非常棒的远程文件管路软件

It supports multiple cloud services as well as WebDAV,FTP and SFTP protocol 
可以挂载不同的云服务并且支持WebDAV, FTP和SFTP协议

It can mount your remote files like a local drive/folder 
它能将你云上或者远程的文件（夹）挂载到本地的资源管理器

This is the home page: https://www.raidrive.com/
官方网站是: https://www.raidrive.com/

**Comment by chawyehsu** [comment]
https://www.raidrive.com/download
没有合适的下载方式

**Comment by yiwenleo** [comment]
谢谢
