### ISSUE TITLE
redis-desktop-manager@2020.2: hash check failed

### ISSUE THREAD

**Issue by wangxianl** [chawyehsu/dorado#167]
App:         dorado/redis-desktop-manager
URL:         https://github.com/lework/RedisDesktopManager-Windows/releases/download/2020.2/redis-desktop-manager-2020.2.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    d152cfd1b7d9c9aef8b66d170cf004b0d62880831b1b35b86f75a7ac4ea70ed8
Actual:      ed94b4db5acb61371124bd5362434da5233bb5e294cb77eaceee949be995a776

**Comment by chawyehsu** [comment]
please re-try

**Comment by wangxianl** [comment]
thank you,it works
