### ISSUE TITLE
[Request] 请求收录WPD隐私管理工具

### ISSUE THREAD

**Issue by yiwenleo** [chawyehsu/dorado#172]
这款软件通过调整 Windows 的本地策略、开启关闭服务、计划、设置防火墙、软件卸载、系统权限设置、系统微调优化等多个方面，来保证你的系统安全以及保护你的隐私信息不轻易被泄露。
官网及下载： https://wpd.app/
Requirements
.NET Framework 4.5+

**Comment by chawyehsu** [comment]
[Extras/wpd](https://github.com/ScoopInstaller/Extras/blob/master/bucket/wpd.json)
