### ISSUE TITLE
🙋‍把experiment单独成一个bucket

### ISSUE THREAD

**Issue by Meng5in** [chawyehsu/dorado#174]
能麻烦大佬把experiment单独做成一个bucket吗？
这样就不会有我这种仅仅眼馋lavfilters和QQ的人，看到了但安装不了的心痒难耐了。
等更完美的解决方案出现时再将app移到dorado bucket，类似于QQ这种可以在json里加notes，提示安装者如何解决QQProtect的问题（似乎issues里有人说这问题解决不了_(:τ」∠)_ ）。
这样experiment就更符合“实验”性质了。
我大概想到两个可能会出现的问题：

- 工作量变大了
- 我现在还不太明白如果将app从一个bucket移到另一个bucket会有什么后果

希望我的小提议能提供个不同的思路_(:τ」∠)_

**Comment by kidonng** [comment]
制作一个 bucket 非常简单，仅仅是将 manifest（JSON 文件）放置在一个 git 仓库中，这个仓库甚至可以是本地仓库，自己动手丰衣足食。
至于你提到的两个应用：
- lavfilters 那个看样子只是没写完而已，我可以考虑接手
- QQ/TIM 之类软件有大量控件注册、注册表修改操作，通过任何非官方安装包的方式进行安装都是事倍功半，更建议使用第三方的绿色版本呢

**Comment by Meng5in** [comment]
谢谢大佬！
我其实在extras里提过issue
https://github.com/lukesampson/scoop-extras/issues/3654
然后有大佬提交过.json文件，但是没被放进bucket
https://github.com/lukesampson/scoop-extras/pull/3675/commits/9a916cefacb94e3842e73cf5939b84bca18d7005
现在明白，原来是因为管理员权限的原因_(:τ」∠)_
因为现阶段水平实在有限，只能看懂一点点json，而且只是LAVFilters没在bucket里找到……
所以只能拜托一下大佬，感谢感谢！

**Comment by kidonng** [comment]
> 然后有大佬提交过.json文件，但是没被放进bucket
> [lukesampson/scoop-extras@9a916ce](https://github.com/lukesampson/scoop-extras/commit/9a916cefacb94e3842e73cf5939b84bca18d7005)
> 现在明白，原来是因为管理员权限的原因_(:τ」∠)_

Scoop 的官方 bucket（除了 `nerdfonts`） 以及这个 bucket 都是尽可能避免需要管理员权限的应用，因为这和 Scoop 的宗旨不符，只能求助于不挑食的第三方 bucket 或是自建。

也感谢你提供的链接，我之前没注意到 LAVFilters 需要使用 rundll32 打开设置界面。如果你已经安装了的话，请重新安装一遍以便使用新 manifest 生成快捷方式。

**Comment by Meng5in** [comment]
在安装的时候如果不用sudo或者管理员权限运行，需要卸载重新使用管理员权限安装。
能直接调用sudo或者直接将sudo作为依赖安装吗？
谢谢！

**Comment by kidonng** [comment]
> 在安装的时候如果不用sudo或者管理员权限运行，需要卸载重新使用管理员权限安装。

这实际上是 Scoop 的老毛病之一，在 installer 里 abort 便会如此。

> 能直接调用sudo或者直接将sudo作为依赖安装吗？

sudo 只是给予管理员权限的方法之一，不应该强制依赖。

---

如果你有更多问题请在相应的 bucket 或通过其他方式询问，这个 issue 就专注于最初的问题。
