### ISSUE TITLE
WeChat nightly自动更新

### ISSUE THREAD

**Issue by Meng5in** [chawyehsu/dorado#209]
WeChat nightly能加入自动更新吗？不然每次更新都要重新卸载安装……
太难了……
我看Firefox-nightly自动更新是“autoupdate”，因为不太懂，不知道加入自动更新有什么困难。
麻烦大佬了……

**Comment by chawyehsu** [comment]
nightly软件更新交给软件本身处理，直接用微信本身的更新功能就行了。

**Comment by Meng5in** [comment]
> nightly软件更新交给软件本身处理，直接用微信本身的更新功能就行了，不需要卸载。

微信自己更新没scoop更新来得快，有时候你还得点一下它才会去检查更新，不点有时候都不知道它有更新……

**Comment by escape0707** [comment]
写manifest倒是不难，但是看这个issue #10

**Comment by chawyehsu** [comment]
我改为 nightly 不是下载页面样式的问题。是因为下载链接没有固定的版本号，以前总是悄悄更新了 `WeChatSetup.exe` 没有更新版本号，导致 hash 经常变。

**Comment by escape0707** [comment]
humm，如果是那个原因的话，也就只有用户在安装wechat的时候会遇到问题，但是只要提交一下hash不匹配的issue也就解决了，等到微信方面更新了新版本号的信息后，已经安装的用户也可以用scoop批量自动更新（即使他们没注意到微信已经有更新了）。

也就是说，这个软件的问题带来的只有需要批准机器人的pr的劳动量的问题？还是说有什么其他不妥的地方呢……

**Comment by escape0707** [comment]
> 
> 
> WeChat nightly能加入自动更新吗？不然每次更新都要重新卸载安装……
> 太难了……
> 我看Firefox-nightly自动更新是“autoupdate”，因为不太懂，不知道加入自动更新有什么困难。
> 麻烦大佬了……

以及，你更新nightly不用卸载。如果你不用自动更新的话，我记得只要在update的时候用一下`-f`开关就好了。

**Comment by Meng5in** [comment]
> 我改为 nightly 不是下载页面样式的问题。是因为下载链接没有固定的版本号，以前总是悄悄更新了 `WeChatSetup.exe` 没有更新版本号，导致 hash 经常变。

怪不得其他不把wechat标注为nightly的bucket总是更新出错。

**Comment by Meng5in** [comment]
> > WeChat nightly能加入自动更新吗？不然每次更新都要重新卸载安装……
> > 太难了……
> > 我看Firefox-nightly自动更新是“autoupdate”，因为不太懂，不知道加入自动更新有什么困难。
> > 麻烦大佬了……
> 
> 以及，你更新nightly不用卸载。如果你不用微信自带的更新的话，我记得只要在update的时候用一下`-f`开关就好了（可能还需要`-k`，你看一下`scoop help update`吧）。

-f是`即使没有新版本也强制升级`的意思。

**Comment by Meng5in** [comment]
> humm，如果是那个原因的话，也就只有发生这种软件发行事故之后，第一次有用户全新安装或从一个更老的版本更新wechat的时候会遇到问题，但是只要提交一下hash不匹配的issue也就解决了，等到微信方面更新了新版本号的信息后，已经安装的用户也可以在scoop中被推送这个更新（即使他们没注意到微信已经有更新了）。
> 
> 也就是说，从nightly换到有版本号的话带来的只有需要批准机器人的pr的劳动量的问题？还是说有什么其他不妥的地方呢……
> 要是有一个不检查hash但是仍然保留版本号的方法就好了。
> 
> 微信乱搞版本和安装包倒是蛮丑陋的Orz。

能不能在`-k`加入到升级命令中去？就是让`scoop update wechat`等于`scoop update wechat -k`？
似乎挺难的…………
不过设置个alias倒是挺容易。

**Comment by escape0707** [comment]
menifest 做不到也不应该能做到这一点

**Comment by kidonng** [comment]
@escape0707 更新日志界面只会记录大版本更新，然而之前频繁导致 hash 变动的是小更新。

我想了一个迂回的解决方案：从腾讯软件中心获取版本号 https://github.com/kidonng/sushi/blob/3ef5511f536cfd354491f2d593964e8be0fecb7b/bucket/wechat.json#L26

**Comment by escape0707** [comment]
@kidonng 强！那我就把我PR关了（
