### ISSUE TITLE
dotnet-desktop-runtime@5.0.0: download via aria2 failed

### ISSUE THREAD

**Issue by RavenMacDaddy** [chawyehsu/dorado#221]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://dotnetcli.blob.core.windows.net/dotnet/Runtime/5.0.0/windowsdesktop-runtime-5.0.0-win-x64.exe
    referer=https://dotnetcli.blob.core.windows.net/dotnet/Runtime/5.0.0/
    dir=C:\users\amand\Scoop\cache
    out=dotnet-desktop-runtime#5.0.0#https_dotnetcli.blob.core.windows.net_dotnet_Runtime_5.0.0_windowsdesktop-runtime-5.0.0-win-x64.exe

ERROR & 'C:\users\amand\Scoop\apps\aria2\current\aria2c.exe' --input-file='C:\users\amand\Scoop\cache\dotnet-desktop-runtime.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6956 --continue --summary-interval 0

**Comment by RavenMacDaddy** [comment]
Do note that the issue persists without aria2 enabled; the URLs seem to be broken.

**Comment by chawyehsu** [comment]
Waiting for upstream to resolve installer archives missing issue.

**Comment by zanderzhng** [comment]
should you find direct link here
https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.0-windows-x64-installer
https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.0-windows-x86-installer

**Comment by chawyehsu** [comment]
> should you find direct link here
> https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.0-windows-x64-installer
> https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.0-windows-x86-installer

Those links contains random strings and are not suitable for the bot to execute autoupdate

**Comment by zanderzhng** [comment]
> > should you find direct link here
> > https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.0-windows-x64-installer
> > https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.0-windows-x86-installer
> 
> Those links contain random strings and are not suitable for the bot to execute autoupdate

I think they just look like random strings while they were perm link actually. I've tried different computers and different day, the link stays the same.
You may check if you get same link as I did.
https://download.visualstudio.microsoft.com/download/pr/92866d29-a298-4cab-b501-a65e43820f97/88d287b9fb4a12cfcdf4a6be85f4a638/aspnetcore-runtime-5.0.0-win-x64.exe
https://download.visualstudio.microsoft.com/download/pr/115edeeb-c883-45be-90f7-8db7b6b3fa2f/6bf92152b2b9fa9c0d0b08a13b60e525/aspnetcore-runtime-5.0.0-win-x86.exe

**Comment by chawyehsu** [comment]
closed by https://github.com/chawyehsu/dorado/commit/ebbf7458a9443687e4e62be57e00f881846f36e1
