### ISSUE TITLE
[Request] 可以给 powershell 安装后添加注册表项吗

### ISSUE THREAD

**Issue by Vixb1122** [chawyehsu/dorado#224]
一些软件是根据注册表项检测powershell的，比如windows terminal和vscode。
使用msi安装powershell后，会[添加注册表项](https://docs.microsoft.com/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1#registry-keys-created-during-installation)，HKLM\Software\Microsoft\PowerShellCore\InstalledVersions\<GUID>。
我看已有的app manifest，有对注册表进行操作的。比如 [enpass](https://github.com/lukesampson/scoop-extras/blob/master/bucket/enpass.json) 和[inno-script-studio](https://github.com/lukesampson/scoop-extras/blob/master/bucket/inno-script-studio.json)。

**Comment by chawyehsu** [comment]
用 Scoop 管理软件时，我对所有注册表相关的配置操作都持不赞成意见，所以我不会去实现此需求。如果你确实想要该功能，也许可以：

1. 用 msi 执行常规安装
2. 用 winget 进行安装管理
3. 实现你自己的 manifest

**Comment by Vixb1122** [comment]
好吧，我也没好的思路在autoupdate中，获取<GUID>，就此作罢吧。
