### ISSUE TITLE
qbittorrent-enhanced 便携版本支持

### ISSUE THREAD

**Issue by Hxppdv** [chawyehsu/dorado#255]
库里的qbittorrent-enhanced 的配置文件是存储在appdata文件夹里的，我觉得如果放在persist文件夹里会更好。

extra仓库里有portable原版的[例子](https://github.com/lukesampson/scoop-extras/blob/master/bucket/qbittorrent-portable.json)。

qbittorrent-enhanced 也有相关的[讨论和解决办法](https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/4#issuecomment-566849820)。

**Comment by escape0707** [comment]
this can be closed now that the pr is merged
