### ISSUE TITLE
[Request] 能否支持下phpstudy

### ISSUE THREAD

**Issue by jiangbo0216** [chawyehsu/dorado#27]
有兴趣一起维护，但是不知道怎么加入，对于bucket维护也不是很熟悉，

建议加入一款软件 phpstudy https://www.xp.cn/download.html

**Comment by h404bi** [comment]
好主意。

**Comment by jiangbo0216** [comment]
如何维护一个bucket呢，想要出份力，
需要哪些预备知识呢


https://github.com/h404bi/dorado/blob/master/bucket/anaconda3.json
类似这个配置项有点多和杂，之前去看过官方文档，
看到还有powershell的知识点

**Comment by h404bi** [comment]
可以先阅读一下官方WIKI：https://github.com/lukesampson/scoop/wiki#concepts

**Comment by jiangbo0216** [comment]
有一个疑问 查了下资料， $在powershell中用来定义变量，这个变量是在bin目录下的ps1文件中定义的吗，或者是scoop中定义的，如果是bin目录定义的，什么时候执行到的呢

还有一个问题，在使用 phpstudy 2019版本没有遇到什么依赖库的问题

**Comment by h404bi** [comment]
> 有一个疑问 查了下资料， $在powershell中用来定义变量，这个变量是在bin目录下的ps1文件中定义的吗，或者是scoop中定义的，如果是bin目录定义的，什么时候执行到的呢

你指的是 manifest 里面的变量？manifest 里有一些变量是 scoop 里面定义的，方便设计 manifest 用的。bin 目录是一些维护脚本，方位维护 bucket 用的。比如 `bin\checkver.ps1` 就是用来检查更新的。

> 还有一个问题，在使用 phpstudy 2019版本没有遇到什么依赖库的问题

那可能是 2019 版自动安装了 vc 库，或者默认系统已经有 vc 库了。2019 版改变太多，不太喜欢。
