### ISSUE TITLE
怎么自建bucket

### ISSUE THREAD

**Issue by git-wanglei** [chawyehsu/dorado#28]
你好，刚使用scoop，能交流下，怎么自建bucket吗？

**Comment by huiyifyj** [comment]
自建 `bucket` 一般只需要了解一些 `bucket` 的配置文件 (`JSON文件格式`) 的属性字段的意思就可以。
参考：https://github.com/lukesampson/scoop/wiki/App-Manifests

除了有些软件安装需要一些 `post_install` 属性，着些属性可能需要你会些 `PowerShell`。

**Comment by h404bi** [comment]
最快的办法，Fork 本仓库，在此 Fork 基础上做你自定义的修改。

**Comment by zhoujin7** [comment]
建了一个仓库自用, https://github.com/zhoujin7/tomato/tree/master/bucket , 有3个共享软件不提供安装包.

**Comment by zhoujin7** [comment]
提供一个powershell脚本, 可以用来查询所有可用的app.
https://github.com/zhoujin7/scoop-search/blob/master/scoopSearch.ps1

**Comment by chengxuncc** [comment]
升级软件版本的commit是自动的还是手动的? 比如`wps-cn: Update to version 11.1.0.9501`这个格式是自己打的吗?

**Comment by escape0707** [comment]
@chengxuncc https://github.com/ScoopInstaller/Excavator 会调用 https://github.com/lukesampson/scoop/blob/master/bin/auto-pr.ps1

**Comment by chengxuncc** [comment]
@escape0707 谢谢，已经知道了
