### ISSUE TITLE
[Request] 请求windows上的kde-connect软件。

### ISSUE THREAD

**Issue by Aquaakuma** [chawyehsu/dorado#287]
***name***：KDE Connect
***description***：是一个开源软件，能够让手机和电脑连接，有共享剪切板，发送短信，同步通知，等等功能，类似小米华为的多屏协作，功能强大。
***website***：https://kdeconnect.kde.org
***download***：https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/
***license***：GPL
***special note***：机器人每天都会构建最新版本，所以希望可以用scoop自动管理升级，省去很多麻烦，软件有三种安装版本：EXE、7z、APPX，我尝试过写7z版的安装脚本，但是环境好像有问题，不能直接启动，EXE和APPX可以，可能要设置什么环境变量吧，7z和APPX比较独立，不会修改注册表，比较方便。

**Comment by liangjihua** [comment]
KDE Connect，不翻墙的话，在国内很难下载成功。。。
