### ISSUE TITLE
[Request] 请求添加 坚果云 火绒安全 向日葵远程控制软件

### ISSUE THREAD

**Issue by MingZhao2019** [chawyehsu/dorado#306]
RT，其中向日葵远程找到一个在 https://github.com/everyx/scoop-bucket/blob/master/bucket/SunloginClient.json
但是好像是通过腾讯的软件管家页面来检查更新的。

**Comment by chawyehsu** [comment]
火绒这是绝对不可能的了，安全软件建议通过常规方式安装，况且是内核级的高权限软件，不适合 Scoop 管理。

坚果云见#88。

向日葵我得看看，如果需要注册表/管理员权限操作的话就不适合本 bucket，见 README 说明。这类软件大概率需要提权。

**Comment by MingZhao2019** [comment]
> 火绒这是绝对不可能的了，安全软件建议通过常规方式安装，况且是内核级的高权限软件，不适合 Scoop 管理。
> 
> 坚果云见#88。
> 
> 向日葵我得看看，如果需要注册表/管理员权限操作的话就不适合本 bucket，见 README 说明。这类软件大概率需要提权。

好的，谢谢。另外如果方便能否请教一个问题：仓库bucket里的json 的文件，写好了版本号并且做了更新检测机制的，如果官网的软件更新了，json文件会自动更新吗？包括版本号等，还是要scoop install 之后再手动 scoop update?

**Comment by chawyehsu** [comment]
向日葵整个软件从头到尾都要 admin rights，安装包 installer 类型探测不出来，有 upx 壳脱掉后运行不了。 自带的免安装并不是标所谓的绿色，会释放很多文件到 ProgramData。不适合 Scoop 或者本仓库。建议自行使用。

**Comment by chawyehsu** [comment]
> 好的，谢谢。另外如果方便能否请教一个问题：仓库bucket里的json 的文件，写好了版本号并且做了更新检测机制的，如果官网的软件更新了，json文件会自动更新吗？包括版本号等，还是要scoop install 之后再手动 scoop update?

自动更新
