### ISSUE TITLE
[Request] 请求添加一个FinalShell

### ISSUE THREAD

**Issue by ijry** [chawyehsu/dorado#309]
<!-- **Please describe the app you want to add.**
Final Shell: http://www.hostbuf.com/t/988.html
FinalShell是一体化的的服务器,网络管理软件,不仅是ssh客户端,还是功能强大的开发,运维工具,充分满足开发,运维需求.

**Comment by b4imetu** [comment]
可供参考：
https://github.com/manjaroyyq/Meta/blob/master/bucket/finalshell.json
https://github.com/ViCrack/scoop-bucket/blob/master/bucket/finalshell.json
