### ISSUE TITLE
aegisub: add maintained fork

### ISSUE THREAD

**Issue by kidonng** [chawyehsu/dorado#311]
There is a maintained fork of Aegisub at https://github.com/wangqr/Aegisub. Consider ~~using it as upstream instead~~ (or create a new formula)?

EDIT: looks like Aegisub's got new maintainers: Aegisub/Aegisub#214

**Comment by chawyehsu** [comment]
I was aware of the fork before. Didn't use it as upstream because I wanted to see if there's any chance it could be merged back to the original stream. I know the fork's maintainer is intended to do that.
