### ISSUE TITLE
epicgameslauncher@nightly: decompress error

### ISSUE THREAD

**Issue by qzydustin** [chawyehsu/dorado#333]
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  This is a nightly version. Downloaded files won't be verified.
Installing 'epicgameslauncher' (nightly-20210514) [64bit]
Loading EpicGamesLauncherInstaller.msi from cache.
Extracting EpicGamesLauncherInstaller.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\qzydustin\scoop\apps\epicgameslauncher\nightly-20210514\EpicGamesLauncherInstaller.msi.
Log file:
  ~\scoop\apps\epicgameslauncher\nightly-20210514\msi.log

msi.log: 
=== 记录开始: 2021/5/14  22:43:50 ===
=== 记录停止: 2021/5/14  22:43:58 ===

epic官网显示1603是因为缺少.net3.5，我查看了我的环境，有.net3.5，且重装后依然失败。
直接运行安装包可以安装，但是scoop失败

**Comment by chawyehsu** [comment]
```
scoop install lessmsi
scoop config msiextract_use_lessmsi $true
scoop install epicgameslauncher
```

**Comment by qzydustin** [comment]
solved
