### ISSUE TITLE
epicgameslauncher@12.1.7: decompress error

### ISSUE THREAD

**Issue by Vikiboss** [chawyehsu/dorado#343]

**Comment by Vikiboss** [comment]
Viki ❯❯ ~  11:35 scoop install epicgameslauncher
Installing 'epicgameslauncher' (12.1.7) [64bit]
Loading EpicInstaller-12.1.7.msi from cache
Checking hash of EpicInstaller-12.1.7.msi ... ok.
Extracting EpicInstaller-12.1.7.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\Viki\scoop\apps\epicgameslauncher\12.1.7\EpicInstaller-12.1.7.msi.
Log file:
  ~\scoop\apps\epicgameslauncher\12.1.7\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/chawyehsu/dorado/issues/new?title=epicgameslauncher%4012.1.7%3a+decompress+error

**Comment by chawyehsu** [comment]
https://github.com/chawyehsu/dorado/issues/333#issuecomment-841371544
