### ISSUE TITLE
[Question]下载服务评估和载点选择

### ISSUE THREAD

**Issue by AkariiinMKII** [chawyehsu/dorado#355]
这个思考源于#352，所以这里就以`CrystalDiskInfo`为例，在寻找可选镜像站时发现 mirrors.xtom.com.hk 在使用香港节点时下载速度具有明显优势，而由此提出的问题：
- 在编写manifest时是否要优先选择高速/高质量镜像载点？
- 若需要，需要以哪个地区的结果作为参考？
- 考虑到污染问题（e.g. [TeamViewer](https://github.com/lukesampson/scoop-extras/issues/6181)），是否需要排除大陆载点或降低优先级？

**Comment by chawyehsu** [comment]
> 在编写manifest时是否要优先选择高速/高质量镜像载点？

取决于镜像的权威性和稳定性，比如 `texlive` manifest 就用了官方提供的 ctan 镜像。当权威性和稳定性不足时，更倾向于用源下载链。

> 若需要，需要以哪个地区的结果作为参考？

其实看 manifest 属性，比如 `msys2-cn` 直接用了国内镜像，因为 `-cn` 匹配了用户群。其实官方有镜像 anycast 是最好的，比如上面的 ctan，以及 `firefox` 的 download cdn。

> 考虑到污染问题（e.g. TeamViewer），是否需要排除大陆载点或降低优先级？

还是归到权威性上，载点不可信必然不用。至于怎么判断权威性，这个只能靠投票机制。通常发 PR 和 issue 来公开验证评审即可。

---

由于 scoop 的 manifest scheme 不支持多源配置，载点速度与稳定性问题一直没有好的办法解决。这个只能求个平衡点。

**Comment by AkariiinMKII** [comment]
> > 在编写manifest时是否要优先选择高速/高质量镜像载点？
> 
> 取决于镜像的权威性和稳定性，比如 `texlive` manifest 就用了官方提供的 ctan 镜像。当权威性和稳定性不足时，更倾向于用源下载链。
> 
> > 若需要，需要以哪个地区的结果作为参考？
> 
> 其实看 manifest 属性，比如 `msys2-cn` 直接用了国内镜像，因为 `-cn` 匹配了用户群。其实官方有镜像 anycast 是最好的，比如上面的 ctan，以及 `firefox` 的 download cdn。
> 
> > 考虑到污染问题（e.g. TeamViewer），是否需要排除大陆载点或降低优先级？
> 
> 还是归到权威性上，载点不可信必然不用。至于怎么判断权威性，这个只能靠投票机制。通常发 PR 和 issue 来公开验证评审即可。
> 
> ---
> 
> 由于 scoop 的 manifest scheme 不支持多源配置，载点速度与稳定性问题一直没有好的办法解决。这个只能求个平衡点。

感谢答疑💐
