### ISSUE TITLE
epicgameslauncher@12.1.7: decompress error

### ISSUE THREAD

**Issue by leganck** [chawyehsu/dorado#359]
Installing 'epicgameslauncher' (12.1.7) [64bit]
EpicInstaller-12.1.7.msi (54.2 MB) [===================================================================================================] 100%
Checking hash of EpicInstaller-12.1.7.msi ... ok.
Extracting EpicInstaller-12.1.7.msi ... ERROR Exit code was 1603!
Failed to extract files from D:\DevelopTools\Scoop\apps\epicgameslauncher\12.1.7\EpicInstaller-12.1.7.msi.
Log file:
  D:\DevelopTools\Scoop\apps\epicgameslauncher\12.1.7\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/h404bi/dorado/issues/new?title=epicgameslauncher%4012.1.7%3a+decompress+error

**Comment by Asukaaaaaa** [comment]
same error as you😥

**Comment by chawyehsu** [comment]
https://github.com/chawyehsu/dorado/issues/333#issuecomment-841371544
