### ISSUE TITLE
[Request]请求添加腾讯TIM

### ISSUE THREAD

**Issue by moxuanyuan** [chawyehsu/dorado#370]
个人常见得TIM比QQ用起来清爽
https://tim.qq.com/download.html

**Comment by Meng5in** [comment]
好像之前提过，QQ和TIM都有什么protect那个进程，导致每次安装都出问题。
现在这个bucket里的QQ是.appx里提取的，没有那个什么protect的进程，所以才等安装成功。
不过辣鸡腾讯不知道多久没更新过MSStore里的QQ了。
