### ISSUE TITLE
安装QQ时SSL问题

### ISSUE THREAD

**Issue by Meng5in** [chawyehsu/dorado#371]
安装QQ时总是提示：
`PS C:\Users\Mengxin> scoop install qq`
`Installing qq (9.4.6.0) [64bit]`
`The SSL connection could not be established, see inner exception.`
`URL https://dorado-api.deno.dev/appxqq?dl#/903DB504.46618D74B1ECA_9.4.6.0_x86__a99ra4d2cbcxa.appx.7z is not valid`
小白也不明白是我网络问题还是网页问题……
先谢谢各位答疑💖💖💖

**Comment by chawyehsu** [comment]
网络问题

**Comment by Meng5in** [comment]
谢谢大哥🙏

**Comment by Meng5in** [comment]
🥲🥲🥲请问大概怎么解决这个问题？
我实在没找到解决方法…………
谢谢……

**Comment by Meng5in** [comment]
不行的话可以试试用aria2下载。
