### ISSUE TITLE
snipaste-beta 的配置文件无法正确链接到 persist 目录 

### ISSUE THREAD

**Issue by moxuanyuan** [chawyehsu/dorado#378]
snipaste-beta 安装目录下的 config.ini，安装时确实已经 copy 到 persist 目录 但实际上并没有链接到 persist 目录，依然以文件形式存在安装目录下。

其它bucket的软件都存在同样的问题， 例如 extras/wiztree 的 WizTree3.ini ， extras/rapidee 的 rapidee.ini 等等

但如果是目录则可以链接到persist 目录下的 ，例如 snipaste-beta 安装目录下的 history 目录

我在cmd下使用 dir /a 查看了，如下图

![](https://files.catbox.moe/ruo4j3.png)

我不清楚是不是我的 windows 问题还是其他人都存在同样的问题。。。

**Comment by chawyehsu** [comment]
dir 命令不显示 hardlink，可以用 `fsutil.exe hardlink list <filename>` 查看。

**Comment by moxuanyuan** [comment]
> fsutil

不是显示问题，是实际上文件数据还是保存在安装目录下

我使用了fsutil命令果了

```
PS D:\Scoop\apps\snipaste-beta\2.6.4-Beta> fsutil hardlink list config.ini
\Scoop\apps\snipaste-beta\2.6.4-Beta\config.ini
PS D:\Scoop\apps\snipaste-beta\2.6.4-Beta>
```

**Comment by chawyehsu** [comment]
那可能是 snipaste 软件不遵循 hardlink 逻辑，不支持链接行为，把链接给删除了。你可以卸载后重新安装，再打开软件前用 fsutil 查看一下文件是否有 hardlink 即可验证。

**Comment by moxuanyuan** [comment]
> 那可能是 snipaste 软件不遵循 hardlink 逻辑，不支持链接行为，把链接给删除了。你可以卸载后重新安装，再打开软件前用 fsutil 查看一下文件是否有 hardlink 即可验证。

卸载重新安装了，确实 snipaste 不支持链接行为，把链接给删除了
