### ISSUE TITLE
nvm-windows 更新到 1.1.8了，Fetch 一下

### ISSUE THREAD

**Issue by Vixb1122** [chawyehsu/dorado#402]
https://github.com/coreybutler/nvm-windows/tree/1.1.8

**Comment by chawyehsu** [comment]
仓库里的 nvm-windows 是我当初因上游不支持非管理员模式安装使用的情况下，[Fork](https://github.com/chawyehsu/nvm-windows) 后分发的版本。nvm-windows 已经被我弃用，我不打算再继续跟进维护了。因为上游坚决不把非管理员模式考虑进去，仍坚持管理员提权运行一个本该无需这权限的版本管理器。这与本 bucket 的”哲学“不符，nvm-windows 将被列为 deprecated。

如果你需要替代品，我推荐使用的有：https://volta.sh 、https://github.com/Schniz/fnm
