### ISSUE TITLE
epicgameslauncher@13.0.0: decompress error

### ISSUE THREAD

**Issue by mdmundo** [chawyehsu/dorado#414]
Installing 'epicgameslauncher' (13.0.0) [64bit]
EpicInstaller-13.0.0.msi (150.3 MB) [=========================================================================] 100%
Checking hash of EpicInstaller-13.0.0.msi ... ok.
Extracting EpicInstaller-13.0.0.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\Camper\scoop\apps\epicgameslauncher\13.0.0\EpicInstaller-13.0.0.msi.
Log file:
  ~\scoop\apps\epicgameslauncher\13.0.0\msi.log

**Comment by chawyehsu** [comment]
https://github.com/chawyehsu/dorado/issues/333#issuecomment-841371544
