### ISSUE TITLE
[Request]请求添加BBDown

### ISSUE THREAD

**Issue by DoveBoy** [chawyehsu/dorado#436]
[BBDown](https://github.com/nilaoda/BBDown)一款命令行式哔哩哔哩下载器，方便下载Bilibili上的视频

**Comment by diklios5768** [comment]
https://scoopsearch.github.io/#/apps
这个网站上能搜到好几个BBdown
![image](https://user-images.githubusercontent.com/47837462/140718411-6cc9ca48-ee73-4724-a503-ac112161b3c9.png)

**Comment by DoveBoy** [comment]
> [scoopsearch.github.io/#/apps](https://scoopsearch.github.io/#/apps) 
> 这个网站上能搜到好几个BBdown

感谢！这网站很不错
