### ISSUE TITLE
[Request]ApiPost

### ISSUE THREAD

**Issue by diklios5768** [chawyehsu/dorado#444]
office website: https://www.apipost.cn/
download: https://www.apipost.cn/download.html

**Comment by zhoujin7** [comment]
这个好像只能通过浏览器下载

**Comment by diklios5768** [comment]
现在增加了`auth_key`，是不好下了，以前好像还没有的，可能开始防爬了

**Comment by zhoujin7** [comment]
> 现在增加了`auth_key`，是不好下了，以前好像还没有的，可能开始防爬了

我个人使用就换成postman了  apipost不太安全 他们的人可以看到你的所有接口

**Comment by diklios5768** [comment]
嗯，我两年前提的，现在也不大用了，感谢
