### ISSUE TITLE
[Request]请求添加WiseCare365

### ISSUE THREAD

**Issue by IsaacWangTT** [chawyehsu/dorado#455]
Windows 系统清理和加速工具
清理注册表和磁盘垃圾文件，保护个人隐私记录，提高电脑使用安全。优化系统、提高Windows系统运行速度最好的选择！
官网:https://www.wisecleaner.com/
下载地址下有便携版:https://www.wisecleaner.com/download.html

**Comment by diklios5768** [comment]
> Windows 系统清理和加速工具 清理注册表和磁盘垃圾文件，保护个人隐私记录，提高电脑使用安全。优化系统、提高Windows系统运行速度最好的选择！ 官网:https://www.wisecleaner.com/ 下载地址下有便携版:https://www.wisecleaner.com/download.html

https://scoopsearch.github.io/#/apps?wisecare365
有不少库已经收录了，可以先用着

**Comment by diklios5768** [comment]
https://scoopsearch.github.io/#/apps?wisecare365
有不少库已经收录了，可以先用着
