### ISSUE TITLE
neteasemusic@2.9.6.199543.: decompress error

### ISSUE THREAD

**Issue by tkit1994** [chawyehsu/dorado#457]
Installing 'neteasemusic' (2.9.6.199543.) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 6c622e|OK  |    12MiB/s|D:/Applications/Scoop/cache/neteasemusic#2.9.6.199543.#https_d1.music.126.net_dmusic_cloudmusicsetup2.9.6.199543..exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of cloudmusicsetup2.9.6.199543..exe ... ok.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from D:\Applications\Scoop\apps\neteasemusic\2.9.6.199543.\dl.7z.
Log file:
  D:\Applications\Scoop\apps\neteasemusic\2.9.6.199543.\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/h404bi/dorado/issues/new?title=neteasemusic%402.9.6.199543.%3a+decompress+error

**Comment by DoveBoy** [comment]
同样的问题

**Comment by tkit1994** [comment]
It seems that a careless netease programmer put a dot behind the version number and windows directory cannot end with dot.
```
Failed to extract files from D:\Applications\Scoop\apps\neteasemusic\2.9.6.199543.\dl.7z.
```
How are we going to do with that. The app installed with scoop is broken now :(

**Comment by DoveBoy** [comment]
fix install [neteasemusic](https://github.com/chawyehsu/dorado/pull/459)
