### ISSUE TITLE
epicgameslauncher@13.0.0: decompress error

### ISSUE THREAD

**Issue by s9y6q12** [chawyehsu/dorado#464]
PS C:\Users\SYQ> scoop uninstall chawyehsu/epicgameslauncher
Uninstalling 'epicgameslauncher' ().
'epicgameslauncher' was uninstalled.
PS C:\Users\SYQ> scoop install chawyehsu/epicgameslauncher
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'epicgameslauncher' (13.0.0) [64bit]
Loading EpicInstaller-13.0.0.msi from cache.
Checking hash of EpicInstaller-13.0.0.msi ... ok.
Extracting EpicInstaller-13.0.0.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\SYQ\scoop\apps\epicgameslauncher\13.0.0\EpicInstaller-13.0.0.msi.
Log file:
  ~\scoop\apps\epicgameslauncher\13.0.0\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/chawyehsu/dorado/issues/new?title=epicgameslauncher%4013.0.0%3a+decompress+error
[msi.log](https://github.com/chawyehsu/dorado/files/7611506/msi.log)

**Comment by chawyehsu** [comment]
see #333
