### ISSUE TITLE
[Request]Twinkle Tray: Brightness Slider

### ISSUE THREAD

**Issue by Xm798** [chawyehsu/dorado#480]
**Twinkle Tray** lets you easily manage the brightness levels of multiple monitors.

Homepage: [xanderfrangos/twinkle-tray](https://github.com/xanderfrangos/twinkle-tray)
Download: [Github Release](https://github.com/xanderfrangos/twinkle-tray/releases)
License: [MIT](https://github.com/xanderfrangos/twinkle-tray/blob/master/LICENSE)

**Comment by AkariiinMKII** [comment]
Included in [extras bucket](https://github.com/ScoopInstaller/Extras)

**Comment by Xm798** [comment]
> Included in [extras bucket](https://github.com/ScoopInstaller/Extras)

Thanks!
