### ISSUE TITLE
clash-for-windows: download url changed and auto-update did not work

### ISSUE THREAD

**Issue by Sycamoie** [chawyehsu/dorado#504]
The newer 32-bit version of clash-for-windows is now not under [Clash.for.Windows.Setup.$version.ia32.exe](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.19.6/Clash.for.Windows.Setup.0.19.6.ia32.exe#/dl.7z), but [Clash.for.Windows.$version.ia32.exe](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.19.6/Clash.for.Windows.0.19.6.ia32.exe#/dl.7z) (see the [release page](https://github.com/Fndroid/clash_for_windows_pkg/releases) for details). I am not sure if this is for this specific version only, or it is going to be so for all the following releases.

May this be the cause, now the auto-update action has not updated clash-for-windows to 0.19.6, which was released 2 days ago.

----------------

0.19.6版本的32位clash-for-windows下载地址格式不再是[Clash.for.Windows.Setup.$version.ia32.exe](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.19.6/Clash.for.Windows.Setup.0.19.6.ia32.exe#/dl.7z)， 而是[Clash.for.Windows.$version.ia32.exe](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.19.6/Clash.for.Windows.0.19.6.ia32.exe#/dl.7z) (详见 [release page](https://github.com/Fndroid/clash_for_windows_pkg/releases))。不确定是这个版本这样还是以后都这样。

可能是因为这个原因，自动更新的action没有更新clash-for-windows。

**Comment by Sycamoie** [comment]
Like your bucket, btw. Please tell me if I can do anything for help.

**Comment by AkariiinMKII** [comment]
cfw开发者说下版本改回来

**Comment by Sycamoie** [comment]
> cfw开发者说下版本改回来

要不手动更新一下json？这样下个版本还能自动更新吗？

**Comment by AkariiinMKII** [comment]
> > cfw开发者说下版本改回来
> 
> 要不手动更新一下json？这样下个版本还能自动更新吗？

下版本可以的
