### ISSUE TITLE
[Request] ParaView

### ISSUE THREAD

**Issue by ZenanH** [chawyehsu/dorado#517]
- App name: ParaView
- Description: ParaView is an open-source, multi-platform data analysis and visualization application.
- Website: [https://www.paraview.org/](https://www.paraview.org/)
- Download: [https://www.paraview.org/download/](https://www.paraview.org/download/)
- Licence: [3-Clause BSD](https://www.paraview.org/paraview-license/)

**Comment by chawyehsu** [comment]
[Extras/paraview](https://github.com/ScoopInstaller/Extras/blob/master/bucket/paraview.json)
