### ISSUE TITLE
[Bug] Miniconda 3 安装后提示不清楚

### ISSUE THREAD

**Issue by xiongnemo** [chawyehsu/dorado#543]
在 PowerShell 5 中，所给提示无法直接运行:

https://github.com/chawyehsu/dorado/blob/7714e5bedb10e93c7999359ddebb0035f3b7b0ae/bucket/miniconda3.json#L59

![image](https://user-images.githubusercontent.com/38759782/159842150-d42ea541-a945-4273-aa34-25241ef6ae66.png)

如有可能会提 PR 修复。

**Comment by chawyehsu** [comment]
谢谢，应该是引号转义问题。
