### ISSUE TITLE
aliyundriver url have erroo

### ISSUE THREAD

**Issue by ZhangHaizhao** [chawyehsu/dorado#562]
the url aliyundriver have no speed to download

**Comment by ShaoqiangLu** [comment]
Source is reachable now
[download link](https://tongyongxiezuo.oss-cn-zhangjiakou.aliyuncs.com/desktop/aDrive-desktop/3.4.1/update/win32/ia32/aDrive-3.4.1.exe#/aDrive-3.4.1.7z) from #595
