### ISSUE TITLE
neteasemusic

### ISSUE THREAD

**Issue by ZhangHaizhao** [chawyehsu/dorado#598]
Installing 'neteasemusic' (2.9.9.199909) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 1b2b41|OK  |   3.1MiB/s|D:/Scoop/cache/neteasemusic#2.9.9.199909#https_pd.zwc365.com_https_d1.music.126.net_dmusic_cloudmusicsetup2.9.9.199909.exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of cloudmusicsetup2.9.9.199909.exe ... ok.
Extracting dl.7z ... done.
Linking D:\Scoop\apps\neteasemusic\current => D:\Scoop\apps\neteasemusic\2.9.9.199909
Creating shim for 'cloudmusic'.
Can't shim 'cloudmusic.exe': File doesn't exist.

**Comment by ZhangHaizhao** [comment]
Can't shim 'cloudmusic.exe': File doesn't exist.
can't install netease

**Comment by AkariiinMKII** [comment]
#587
