### ISSUE TITLE
ApiFox [Request]

### ISSUE THREAD

**Issue by sj13824803000** [chawyehsu/dorado#604]
程序员必备的调试工具吖,麻烦加一下
官网: https://www.apifox.cn/

**Comment by ViCrack** [comment]
我在自己的仓库里面刚试了一下，这东西的版本号一般还不好获取

https://github.com/ViCrack/scoop-bucket/blob/f407334f99716c4424e28d30de62f767dc6b4cd6/bucket/apifox.json

**Comment by sj13824803000** [comment]
> 我在自己的仓库里面刚试了一下，这东西的版本号一般还不好获取
> 
> https://github.com/ViCrack/scoop-bucket/blob/f407334f99716c4424e28d30de62f767dc6b4cd6/bucket/apifox.json

牛逼!!!

**Comment by chawyehsu** [comment]
[Extras/apifox](https://github.com/ScoopInstaller/Extras/blob/master/bucket/apifox.json)
