### ISSUE TITLE
epicgameslauncher@13.3.0: decompress error

### ISSUE THREAD

**Issue by 1623382** [chawyehsu/dorado#608]
Installing 'epicgameslauncher' (13.3.0) [64bit]
Loading EpicInstaller-13.3.0.msi from cache.
Checking hash of EpicInstaller-13.3.0.msi ... ok.
Extracting EpicInstaller-13.3.0.msi ... ERROR Exit code was 1603!
Failed to extract files from D:\Scoop\apps\epicgameslauncher\13.3.0\EpicInstaller-13.3.0.msi.
Log file:
  D:\Scoop\apps\epicgameslauncher\13.3.0\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/chawyehsu/dorado/issues/new?title=epicgameslauncher%4013.3.0%3a+decompress+error
=== 记录开始: 2022/6/22  23:53:42 ===
=== 记录停止: 2022/6/22  23:53:51 ===

**Comment by chawyehsu** [comment]
#333
