### ISSUE TITLE
Edge Dev 的疑惑

### ISSUE THREAD

**Issue by wordpure** [chawyehsu/dorado#652]
![图片](https://user-images.githubusercontent.com/68013962/194225524-d88c933e-bfaf-4859-8ea0-49839a042bb8.png)

左侧是通过 [官网](https://www.microsoft.com/en-us/edge/business/download) 下载安装的，右侧是通过 [Scoop](https://github.com/chawyehsu/dorado/blob/master/bucket/microsoftedge-dev.json) 安装的。

虽然版本号都一样，但右侧不知为何没有 dev 标识。

**Comment by chawyehsu** [comment]
仓库里的 Edge 都是直接解包安装，可能破坏了一些常规安装过程中的配置项。不影响使用可以不管，强迫症就使用常规安装吧。
