### ISSUE TITLE
epicgameslauncher@14.2.1: decompress error

### ISSUE THREAD

**Issue by bingoct** [chawyehsu/dorado#669]
➜ scoop update
➜ scoop install dorado/epicgameslauncher
WARN  Purging previous failed installation of epicgameslauncher.
ERROR 'epicgameslauncher' isn't installed correctly.
Removing older version (14.2.1).
'epicgameslauncher' was uninstalled.
Installing 'epicgameslauncher' (14.2.1) [64bit] from dorado bucket
Loading EpicInstaller-14.2.1.msi from cache
Checking hash of EpicInstaller-14.2.1.msi ... ok.
Extracting EpicInstaller-14.2.1.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\bingo\scoop\apps\epicgameslauncher\14.2.1\EpicInstaller-14.2.1.msi.
Log file:
  ~\scoop\apps\epicgameslauncher\14.2.1\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/chawyehsu/dorado/issues/new?title=epicgameslauncher%4014.2.1%3a+decompress+error

➜ bat ..\scoop\apps\epicgameslauncher\14.2.1\msi.log
───────┬─────────────────────────────────────────────────────────────
       │ File: ..\scoop\apps\epicgameslauncher\14.2.1\msi.log   <UTF-16LE>
───────┼─────────────────────────────────────────────────────────────
   1   │ === 记录开始: 2022/11/15  17:18:54 ===
   2   │ === 记录停止: 2022/11/15  17:19:02 ===
───────┴─────────────────────────────────────────────────────────────

**Comment by chawyehsu** [comment]
#333
