### ISSUE TITLE
[Request] Tableau Desktop

### ISSUE THREAD

**Issue by chawyehsu** [chawyehsu/dorado#67]
## app name
Tableau Desktop

## description
interactive data visualization software

## website
https://www.tableau.com/

## download
https://www.tableau.com/support/releases
https://help.tableau.com/current/desktopdeploy/en-us/desktop_deploy_automate.htm

**Comment by h404bi** [comment]
> The Tableau Desktop/Public product actually **adds registry keys and folders** to the host machine during an install in order to do it's work - so unfortunately it's not quite as simple as carrying around an install on a thumbdrive --- https://community.tableau.com/thread/122747
