### ISSUE TITLE
epicgameslauncher@14.2.1: decompress error

### ISSUE THREAD

**Issue by trimr** [chawyehsu/dorado#670]
Extracting EpicInstaller-14.2.1.msi ... ERROR Exit code was 1603!
Failed to extract files from D:\scoop\apps\epicgameslauncher\14.2.1\EpicInstaller-14.2.1.msi.
Log file:
  D:\scoop\apps\epicgameslauncher\14.2.1\msi.log

**Comment by chawyehsu** [comment]
#333
