### ISSUE TITLE
[Request] Powershell在main bucket已经有了，是否在本bucket中同步清单配置？

### ISSUE THREAD

**Issue by cesaryuan** [chawyehsu/dorado#686]
Powershell在[main bucket](https://github.com/ScoopInstaller/Main/blob/master/bucket/pwsh.json)已经有了，是否应该在本bucket中同步清单配置？

main中的清单和大佬的bucket中的清单定义有些不同，前者有persist定义。

**Comment by chawyehsu** [comment]
名字不一样，需要用 main 里的安装 pwsh 就行。
