### ISSUE TITLE
dingtalk@7.0.10.3169101: download via aria2 failed

### ISSUE THREAD

**Issue by fungtion** [chawyehsu/dorado#703]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://dtapp-pub.dingtalk.com/dingtalk-desktop/win_installer/Release/DingTalk_v7.0.10.3169101.exe#/dl.7z
    referer=https://dtapp-pub.dingtalk.com/dingtalk-desktop/win_installer/Release/DingTalk_v7.0.10.3169101.exe#/
    dir=C:\Users\fhxnw\scoop\cache
    out=dingtalk#7.0.10.3169101#https_dtapp-pub.dingtalk.com_dingtalk-desktop_win_installer_Release_DingTalk_v7.0.10.3169101.exe_dl.7z

ERROR & 'C:\Users\fhxnw\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\fhxnw\scoop\cache\dingtalk.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6136 --continue --summary-interval=0 --auto-save-interval=1

**Comment by chawyehsu** [comment]
https://github.com/chawyehsu/dorado/commit/a829c24dcbb758d8aa03ebdd812dbb0432c64a9d
