### ISSUE TITLE
[Request]希望能够添加另外一个第三方的网易云播放器-HyPlayer 

### ISSUE THREAD

**Issue by szqcuckoo** [chawyehsu/dorado#708]
HyPlayer 
第三方的网易云播放器，很合我的胃口
这是 GitHub 的 release 的链接 [HyPlayer ](https://github.com/HyPlayer/HyPlayer/releases/tag/2.1.35.5429)

**Comment by ErrorPower2001** [comment]
好像不行，HyPlayer自行打包成了msix格式，scoop没有软件可以部署

**Comment by szqcuckoo** [comment]
原来如此，感谢！
