### ISSUE TITLE
[Request]picpick

### ISSUE THREAD

**Issue by ni87** [chawyehsu/dorado#74]
## App name

PicPick

## description:

一款全能的设计工具，并且这款工具适宜每个人使用
一个全功能的屏幕截图工具,直观的图像编辑器,颜色选择器,颜色调色板,像素标尺,量角器,瞄准线和白板等等。
官方直接提供portable版本

## website

[https://picpick.app/zh](https://picpick.app/zh)

## download
[https://picpick.app/zh/start?download=portable](https://picpick.app/zh/start?download=portable)

**Comment by FDUZS** [comment]
不知你是否发现，这个其实在 'extras' bucket 已有收录。

```
Zheng :: ~ » scoop info picpick
Name: picpick
Description: A full-featured screen capture tool, intuitive image editor, color picker and more
Version: 5.1.1
Website: https://picpick.app
License: Shareware (https://picpick.app/en/download)
Manifest:
  D:\Scoop\buckets\extras\bucket\picpick.json
Installed:
  D:\Scoop\apps\picpick\5.1.1
Binaries:
  picpick.exe
```
