### ISSUE TITLE
[bug] ReIcon v2 (sordum)

### ISSUE THREAD

**Issue by furopi** [chawyehsu/dorado#744]
I have some trouble installing ReIcon v2 from sordum. Please see the log below...

Installing 'reicon' (2.0) [64bit] from dorado bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 189442|OK  |   5.3MiB/s|C:/Users/XXX/scoop/cache/reicon#2.0#https_www.sordum.org_files_restore-desktop-icon-layouts_ReIcon.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of ReIcon.zip ... ERROR Hash check failed!
App:         dorado/reicon
URL:         https://www.sordum.org/files/restore-desktop-icon-layouts/ReIcon.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    af2e08378d538229b18ec33c7124b98f16bbb382f372c5abf9ea6fdba5cfb1b4
Actual:      10d000e05b59022656900672041e0b92ff61b506f457d857fb0516e6e06791b3

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/chawyehsu/dorado/issues/new?title=reicon%402.0%3a+hash+check+failed

**Comment by AkariiinMKII** [comment]
#757
