### ISSUE TITLE
[bug] winlibs-mingw-llvm-ucrt can't be updated by github-bot

### ISSUE THREAD

**Issue by yenfeng-shetiko** [chawyehsu/dorado#759]
winlibs-mingw-llvm-ucrt released four days ago. But github-actions not update it.

**Comment by yenfeng-shetiko** [comment]
It seems that many of winlibs packages has this problem, i'm not sure.

**Comment by chawyehsu** [comment]
Fixed in https://github.com/chawyehsu/dorado/commit/eb9362fcdd63372766ab4a934431a6a6dcfe0f31
