### ISSUE TITLE
questions about installing exe software

### ISSUE THREAD

**Issue by echoiron** [chawyehsu/dorado#77]
### 解压文件中依然存在压缩文件

> 描述：安装exe软件，该软件解压后依然存在一个app.7z文件，而该压缩文件的主程序都在其中，如果直接指定其中的快捷键方式，则会提示报错。

请问有比较好的解决方式吗?

**Comment by h404bi** [comment]
You can use functions provided in [decompress.ps1](https://github.com/lukesampson/scoop/blob/a9fa775d59b14e7dce335313faa0eff855469764/lib/decompress.ps1) to decompress nested archives and create shortcuts for files inside the nested archive. More documents in the [wiki](https://github.com/lukesampson/scoop/wiki/App-Manifests).

**Comment by dajiiu** [comment]
thanks
