### ISSUE TITLE
The DandanPlay download URL is not available

### ISSUE THREAD

**Issue by ICE-GB** [chawyehsu/dorado#787]

**Comment by chawyehsu** [comment]
The [portable version](https://github.com/chawyehsu/dorado/blob/master/bucket/dandanplay.json) (zip package) is not provided anymore on their website. Is there any way to just extract the program from the installer? @kaedei (Sorry for the ping) but I don't know how to handle with its new installer.

**Comment by kaedei** [comment]
> The [portable version](https://github.com/chawyehsu/dorado/blob/master/bucket/dandanplay.json) (zip package) is not provided anymore on their website. Is there any way to just extract the program from the installer? @kaedei (Sorry for the ping) but I don't know how to handle with its exe installer.

可以通过命令行提取安装包中的文件：
`dandanplay-x64_14.4.1.exe /extract D:\temp\dandanplay`
需要先保证目标文件夹已经存在。
解压后的播放器文件会释放在一个随机命名的子文件夹中，例如 `D:\temp\dandanplay\C08AD96`

portable版本现在在网盘上发布，在官网的“从网盘下载(2)”处可以找到

**Comment by chawyehsu** [comment]
谢谢！

**Comment by SpecterShell** [comment]
> > The [portable version](https://github.com/chawyehsu/dorado/blob/master/bucket/dandanplay.json?rgh-link-date=2023-12-06T05%3A08%3A41.000Z) (zip package) is not provided anymore on their website. Is there any way to just extract the program from the installer? [@kaedei](https://github.com/kaedei?rgh-link-date=2023-12-06T05%3A08%3A41.000Z) (Sorry for the ping) but I don't know how to handle with its exe installer.
> 
> 可以通过命令行提取安装包中的文件： `dandanplay-x64_14.4.1.exe /extract D:\temp\dandanplay` 需要先保证目标文件夹已经存在。 解压后的播放器文件会释放在一个随机命名的子文件夹中，例如 `D:\temp\dandanplay\C08AD96`
> 
> portable版本现在在网盘上发布，在官网的“从网盘下载(2)”处可以找到

您好，官网现在好像也不提供安装包了，如果服务器资源紧张的话能否考虑通过GitHub releases上传安装包来分流？

**Comment by kaedei** [comment]
> > > The [portable version](https://github.com/chawyehsu/dorado/blob/master/bucket/dandanplay.json?rgh-link-date=2023-12-06T05%3A08%3A41.000Z) (zip package) is not provided anymore on their website. Is there any way to just extract the program from the installer? [@kaedei](https://github.com/kaedei?rgh-link-date=2023-12-06T05%3A08%3A41.000Z) (Sorry for the ping) but I don't know how to handle with its exe installer.
> > 
> > 
> > 可以通过命令行提取安装包中的文件： `dandanplay-x64_14.4.1.exe /extract D:\temp\dandanplay` 需要先保证目标文件夹已经存在。 解压后的播放器文件会释放在一个随机命名的子文件夹中，例如 `D:\temp\dandanplay\C08AD96`
> > portable版本现在在网盘上发布，在官网的“从网盘下载(2)”处可以找到
> 
> 您好，官网现在好像也不提供安装包了，如果服务器资源紧张的话能否考虑通过GitHub releases上传安装包来分流？

感谢反馈，现在可以从这个仓库下载安装包和便携版：https://github.com/kaedei/dandanplay/releases
之后我会把github release也加到发布流水线中
