### ISSUE TITLE
[Request] Rime Input Method Engine

### ISSUE THREAD

**Issue by SiyuChen** [chawyehsu/dorado#84]
Could you please add Rime Input Method Engine to the bucket? It's probably the best Input engine Engine for Chinese. Thanks in advance!

You could find more information on https://rime.im/

**Comment by h404bi** [comment]
https://github.com/h404bi/dorado/issues/39#issuecomment-549025063
I think rime (and all other input methods) can't work (perfectly) without admin rights?
