### ISSUE TITLE
utools@5.1.0: download via aria2 failed

### ISSUE THREAD

**Issue by SwingURM** [chawyehsu/dorado#843]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: d84889|ERR |       0B/s|E:/Scoop/cache/utools#5.1.0#https_res.u-tools.cn_version2_uTools-5.1.0.exe_dl.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://res.u-tools.cn/version2/uTools-5.1.0.exe#/dl.7z
    referer=https://res.u-tools.cn/version2/uTools-5.1.0.exe#/
    dir=E:\Scoop\cache
    out=utools#5.1.0#https_res.u-tools.cn_version2_uTools-5.1.0.exe_dl.7z

ERROR & 'E:\Scoop\apps\aria2\current\aria2c.exe' --input-file='E:\Scoop\cache\utools.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=16 --max-connection-per-server=16 --min-split-size=4M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3556 --continue --summary-interval=0 --auto-save-interval=1 --all-proxy='127.0.0.1:7897'

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/chawyehsu/dorado/issues/new?title=utools%405.1.0%3a+download+via+aria2+failed

**Comment by SwingURM** [comment]
The URL is now https://open.u-tools.cn/download/uTools-5.1.1.exe

**Comment by wanstarge** [comment]
我试了下，将https://res.u-tools.cn/version2全部替换为https://open.u-tools.cn/download就可以下载了，但是我不确定其他检查更新什么的会不会有影响，我还没有深入了解这些东西

**Comment by wanstarge** [comment]
我试了下，将[https://res.u-tools.cn/version2](https://res.u-tools.cn/version2)全部替换为[https://open.u-tools.cn/download](https://open.u-tools.cn/download)就可以下载了，但是我不确定其他检查更新什么的会不会有影响，我还没有深入了解这些东西

**Comment by SwingURM** [comment]
I try to modify the url in previous manifest, found that 5.x version fails to launch after installation, while 4.3.2 version works well after modify the url. Maybe installation behavior has changed in 5.x version and i can't figure out.

**Comment by SwingURM** [comment]
I try to modify the url in previous manifest, found that 5.x version fails to launch after installation, while 4.3.2 version works well after modify the url. Maybe installation behavior has changed in 5.x version and i can't figure out.
