### ISSUE TITLE
aliyundrive@4.15.0: Download failed

### ISSUE THREAD

**Issue by jqk** [chawyehsu/dorado#850]
远程服务器返回错误: (403) 已禁止。 ERROR This application failed to install: dorado/aliyundrive

实际上，json文件中的链接放到浏览器中有效，可下载。但scoop返回：
ERROR 远程服务器返回错误: (403) 已禁止。

兄弟看看到底是咋回事

**Comment by jqk** [comment]
https://cdn.aliyundrive.net/downloads/apps/desktop/aDrive-4.15.0.exe
放到浏览器也可下载，但手工放到json中，得到的错误是一样的，不知哪里有问题。

另外，关于utools。安装正常，但启动后连闪退都谈不上。
4.x正常安装并启动。此时安装5.1，再启动，会把4.x的界面调出来，证明安装有一定效果。但如果退出4.x，再启动，就是刚刚说的现象。
用下载的文件执行安装，到是没问题的，但用scoop安装，就会运行不出来。
如果能一并解决，万分感谢。俺自己水平太低，整不明白。

谢谢

**Comment by zuluion** [comment]
+1
