### ISSUE TITLE
aliyundrive@4.16.0: download via aria2 failed

### ISSUE THREAD

**Issue by weishengovo** [chawyehsu/dorado#854]
PS C:\Users\weiovo> scoop install dorado/aliyundrive
WARN  Purging previous failed installation of aliyundrive.
ERROR 'aliyundrive' isn't installed correctly.
Removing older version (4.16.0).
'aliyundrive' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'aliyundrive' (4.16.0) [64bit] from 'dorado' bucket
Starting download with aria2 ...
Download: 06/13 22:53:15 [ERROR] CUID#8 - Download aborted. URI=https://cdn.aliyundrive.net/downloads/apps/desktop/updatDownload: Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://cdn.aliyundrive.net/downloads/apps/desktop/updateDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 6765d8|ERR |       0B/s|C:/Users/weiovo/scoop/cache/aliyundrive#4.16.0#https_cdn.aliyundrive.net_downloads_apps_desktop_update_4.16.0_win32_ia32_aDrive-4.16.0.exe_aDrive-4.16.0.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://cdn.aliyundrive.net/downloads/apps/desktop/update/4.16.0/win32/ia32/aDrive-4.16.0.exe#/aDrive-4.16.0.7z
    referer=https://cdn.aliyundrive.net/downloads/apps/desktop/update/4.16.0/win32/ia32/aDrive-4.16.0.exe#/
    dir=C:\Users\weiovo\scoop\cache
    out=aliyundrive#4.16.0#https_cdn.aliyundrive.net_downloads_apps_desktop_update_4.16.0_win32_ia32_aDrive-4.16.0.exe_aDrive-4.16.0.7z

ERROR & 'C:\Users\weiovo\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\weiovo\scoop\cache\aliyundrive.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=13284 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/chawyehsu/dorado/issues/new?title=aliyundrive%404.16.0%3a+download+via+aria2+failed

**Comment by weishengovo** [comment]
https://cdn.aliyundrive.net/downloads/apps/desktop/update/4.16.0/win32/ia32/aDrive-4.16.0.exe#/aDrive-4.16.0.7z
    referer=https://cdn.aliyundrive.net/downloads/apps/desktop/update/4.16.0/win32/ia32/aDrive-4.16.0.exe#/
    dir=C:\Users\weiovo\scoop\cache
    out=aliyundrive#4.16.0#https_cdn.aliyundrive.net_downloads_apps_desktop_update_4.16.0_win32_ia32_aDrive-4.16.0.exe_aDrive-4.16.0.7z

**Comment by GavinChuhhhh** [comment]
+1, same error

**Comment by freeok** [comment]
aDrive 最新的下载地址：https://cdn.aliyundrive.net/downloads/apps/desktop/aDrive-4.16.0.exe
