### ISSUE TITLE
imewlconverter 的exe路径错了

### ISSUE THREAD

**Issue by Antecer** [chawyehsu/dorado#856]
![image](https://github.com/chawyehsu/dorado/assets/8684916/6092ceb2-a8a8-4e95-b51d-6279d26fb9ee)

![image](https://github.com/chawyehsu/dorado/assets/8684916/8abf09ac-07a6-4298-bee1-403bee5148cc)

exe文件路径多了一层publish

**Comment by chawyehsu** [comment]
https://github.com/chawyehsu/dorado/commit/d5f7404bc8bc869bb8aca270c9a5f7a18b8beef5
