### ISSUE TITLE
Creating shortcut for 网易UU (launcher.exe) failed

### ISSUE THREAD

**Issue by icecreamZeng** [chawyehsu/dorado#896]
app：neteaseuu
version ：5.21.0.5034
msg:
Creating shortcut for 网易UU (launcher.exe) failed: Couldn't find C:\Application\Scoop\apps\neteaseuu\current\launcher.exe

**Comment by kicre** [comment]
似乎是启动文件更名为 uu_launcher.exe 的原因
![图片](https://github.com/user-attachments/assets/3d22ea73-dddb-4a9c-a53d-eb986605391c)
