### ISSUE TITLE
[Request]:   hash error   

### ISSUE THREAD

**Issue by Super1Windcloud** [chawyehsu/dorado#912]
### Check list

- [X] I confirm that the package does not exist in this bucket or any other official buckets such as Main and Extras.
- [X] I confirm that there is no existing request for the package in this bucket or any other official bucket. (You should browse issue tracker of official buckets before submitting this request if you are not sure.)
- [X] I believe that the package is suitable to be submitted to this bucket. (If it's not then you should submit the request to official buckets.)
- [X] I understand that the owner of this bucket has the final decision on whether or not give a response to the request. (This is anyway a personal bucket and the owner may not be willing to accept packages they don't use.)

### Name

todesk 

### Description

can't  install   

### Homepage

todesk

### Download Link(s)

todesk 

### License

MIT

### Other information

![Uploading image.png…]()

**Comment by Super1Windcloud** [comment]
![image](https://github.com/user-attachments/assets/4af48425-600f-4c00-9f7c-5a2cb625adbe)

**Comment by zuluion** [comment]
v4.7.5.3 Hash is b51bb47d3f9e58ac12d55fee568e950aa9811e5d1655a15d8ed1af28c3112bd4
