### ISSUE TITLE
clash-verge-rev已经升级到2.0.1了, 官方没有便携版下载了

### ISSUE THREAD

**Issue by zhoujin7** [chawyehsu/dorado#936]
clash-verge-rev已经升级到2.0.1了, 官方没有便携版下载了

安装exe后, 还要执行uninstall-service和install-service

**Comment by lee88688** [comment]
可以考虑参考，[extras仓库的实现](https://github.com/ScoopInstaller/Extras/blob/master/bucket/clash-verge-rev.json)，但是没有便携版，升级到这个版本之后配置还能继续使用吗？
